version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/root/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot -w /var/www/certbot
      -d kazancevegor.online -d www.kazancevegor.online
      --email kazanceve.gor@gmail.com --agree-tos --no-eff-email
    networks:
      - app-network


  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/school_db
      - JWT_SECRET=${JWT_SECRET}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_WEBHOOK_URL=${BOT_WEBHOOK_URL}
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: superAdmin
      MONGO_INITDB_ROOT_PASSWORD: Otebitesotmenya1
    command: >
      --bind_ip_all
      --auth
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=https://kazancevegor.online/api
      - PORT=3001
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
